
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package recuperacionPaginas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 5;
  public static final int ALINEACION = 32;
  public static final int PAGINA = 14;
  public static final int SITIO_WEB = 3;
  public static final int PARAMETRO_DE_PAGINA = 18;
  public static final int NOMBRE = 8;
  public static final int ANCHO = 36;
  public static final int ORACION = 12;
  public static final int COMPONENTES = 16;
  public static final int VIDEO = 40;
  public static final int ETIQUETAS = 17;
  public static final int MENU = 41;
  public static final int PARAMETROS_SITIO_WEB = 6;
  public static final int IGUAL = 9;
  public static final int TITULO = 28;
  public static final int COMPONENTE = 19;
  public static final int PADRE = 30;
  public static final int ID = 11;
  public static final int EOF = 0;
  public static final int PARAMETRO_SITIO_WEB = 7;
  public static final int error = 1;
  public static final int COMILLA = 10;
  public static final int FECHA_MODIFICACION = 26;
  public static final int MAYOR_QUE = 4;
  public static final int ATRIBUTOS = 21;
  public static final int DIRECCION = 23;
  public static final int ATRIBUTO = 20;
  public static final int COLOR = 33;
  public static final int USUARIO_MODIFICACION = 27;
  public static final int FECHA_CREACION = 25;
  public static final int USUARIO_CREACION = 24;
  public static final int IMAGEN = 39;
  public static final int PARRAFO = 38;
  public static final int ORIGEN = 34;
  public static final int ETIQUETAS_MENU = 37;
  public static final int SITIO = 29;
  public static final int PARAMETROS_DE_PAGINA = 15;
  public static final int MENOR_QUE = 2;
  public static final int TEXTO = 31;
  public static final int PAGINAS_SITIO_WEB = 13;
  public static final int ETIQUETA = 22;
  public static final int ALTURA = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENOR_QUE",
  "SITIO_WEB",
  "MAYOR_QUE",
  "DIAGONAL",
  "PARAMETROS_SITIO_WEB",
  "PARAMETRO_SITIO_WEB",
  "NOMBRE",
  "IGUAL",
  "COMILLA",
  "ID",
  "ORACION",
  "PAGINAS_SITIO_WEB",
  "PAGINA",
  "PARAMETROS_DE_PAGINA",
  "COMPONENTES",
  "ETIQUETAS",
  "PARAMETRO_DE_PAGINA",
  "COMPONENTE",
  "ATRIBUTO",
  "ATRIBUTOS",
  "ETIQUETA",
  "DIRECCION",
  "USUARIO_CREACION",
  "FECHA_CREACION",
  "FECHA_MODIFICACION",
  "USUARIO_MODIFICACION",
  "TITULO",
  "SITIO",
  "PADRE",
  "TEXTO",
  "ALINEACION",
  "COLOR",
  "ORIGEN",
  "ALTURA",
  "ANCHO",
  "ETIQUETAS_MENU",
  "PARRAFO",
  "IMAGEN",
  "VIDEO",
  "MENU"
  };
}

